name: ministerio_medioambienteapkrd
description: "Aplicacion para el ministerio de medio ambiente de RD"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  carousel_slider: ^5.1.1
  google_maps_flutter: ^2.6.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  video_player: ^2.8.6
  geolocator: ^12.0.0
  provider: ^6.1.2
  image: ^4.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imagenes/ministerio.png" 

flutter:
  uses-material-design: true

  assets:
    - assets/imagenes/
    - assets/desarrollador/




